- name: create kube folder
  file:
    path: "/home/{{ user.username }}/.kube/"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
  delegate_to: "{{ bastion }}" 
  loop: "{{ clusters | map(attribute='users') | list | flatten }} | product(groups['bastion_hosts']) |list"
  loop_control:
    loop_var: user_bastion
  vars:
    user: "{{ user_bastion[0] }}"
    bastion: "{{ user_bastion[1] }}"
  become: true

- name: Copy merged kubeconfig to user’s home folder
  ansible.builtin.copy:
    src: "/tmp/final-kubeconfigs/{{ user.username }}.conf"
    dest: "/home/{{ user.username }}/.kube/config"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: '0600'
  delegate_to: "{{ bastion }}" 
  loop: "{{ clusters | map(attribute='users') | list | flatten }} | product(groups['bastion_hosts']) |list"
  loop_control:
    loop_var: user_bastion
  vars:
    user: "{{ user_bastion[0] }}"
    bastion: "{{ user_bastion[1] }}"
  become: true
